templates:
  global:
    pyload:
      api: http://localhost:8888/api
      queue: yes
      username: admin
      password: blubblub
      parse_url: no
      multiple_hoster: yes
    email:
      from: xxxxx@gmail.com
      to: uGpxxxxxxqRMHsebfUPwmi2a@api.pushover.net
      smtp_host: smtp.gmail.com
      smtp_port: 587
      smtp_username: xxxx
      smtp_password: xxxx
      smtp_tls: yes
      template: accepted
  tv_ger:
    series:
      settings:
        720p:
          exact: yes
          propers: 3 days
          quality: 720p+
          identified_by: ep
      720p:
        - Rectify
        - Intelligence
        - True Detective
        - New Girl
        - Hannibal
        - Homeland
        - The Following
        - Game of Thrones
        - Sherlock
        - White Collar
        - The Big Bang Theory
        - Arrow
        - The Walking Dead
        - Elementary
        - Lilyhammer
        - Boardwalk Empire
        - Helix
        - Schulz in the Box
        - The Americans 2013
        - The Americans (2013)
        - House of cards
        - Vikings
        - Believe
        - Ripper Street
  tv_eng:
    series:
      settings:
        720p:
          exact: yes
          propers: 3 days
          quality: 720p+
          identified_by: ep
      720p:
        - The Big Bang Theory
        - Game of Thrones
        - Bering Sea Gold
        - Gravity Falls
        - Sherlock
        - Gold Rush Alaska
        - New Girl
        - Jungle Gold
        - The Walking Dead
  movies:
    imdb_required: yes
    imdb:
      min_score: 6.0
      min_year: 1990
      reject_genres:
        - News
        - Sport
        - Documentary
    imdb_lookup: yes
    manipulate:
      - title:
          replace:
            regexp: (?i)\b(.fancut|.german|.uncut|.extended|.se|.dubbed|.dl|.dts|.ac3|.ac3d|.x264*)\b
            format: ''
    regexp:
      reject:
      - \b(1080p)\b: {from: title}
      - \b(COMPLETE)\b: {from: title}
      - \b(Eroti(c|k))\b: {from: title}
      - \b(sub(s|bed))\b: {from: title}
      - \b(XXX)\b: {from: title} 
      - \b(S\d{1,2})\b: {from: title}
      - \b(S\d+E\d+)\b: {from: title}
      - \b(SBS)\b: {from: title}
schedules:
  - tasks: '*'
    interval:
      minutes: 30
tasks:
  serienjunkies:
    inputs:
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=11ed976a0103577b109a2d71ea61d51e&_render=rss&page=1
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=11ed976a0103577b109a2d71ea61d51e&_render=rss&page=2
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=11ed976a0103577b109a2d71ea61d51e&_render=rss&page=3
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=11ed976a0103577b109a2d71ea61d51e&_render=rss&page=4
    accept_all: no
    template: tv_ger
    #disable_builtins: [seen, remember_rejected]
    #exists_series: /media/5a24e136-09b9-48e1-95db-b44d5db3e28a/Medien/TV Shows  
    serienjunkies:
      language: de
      hoster: ul
  Movies_720p:
    inputs:
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=e1269fa803ac490d60b63db37e98accd&_render=rss
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=3377a3dcc889527660e9065d7f008829&_render=rss
    accept_all: no
    template: movies
    #exists_movie: /media/5a24e136-09b9-48e1-95db-b44d5db3e28a/Medien/Movies
    #disable_builtins: [seen, remember_rejected]
